# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 11:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_event'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='event',
            new_name='eventss',
        ),
    ]
