# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20170325_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventss',
            name='name',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='users.clubs'),
        ),
    ]
