# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 12:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_eventss_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventss',
            name='name',
            field=models.ForeignKey(default='', max_length=100, on_delete=django.db.models.deletion.CASCADE, to='users.clubs'),
        ),
    ]
