# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 12:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_eventss_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventss',
            name='name',
        ),
        migrations.DeleteModel(
            name='eventss',
        ),
    ]
