# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 13:16
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_student_judge'),
    ]

    operations = [
        migrations.CreateModel(
            name='judge_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(max_length=100)),
                ('industry_exp', models.IntegerField(default=0)),
                ('about', models.CharField(max_length=500)),
                ('dob', models.DateField(default=datetime.date.today)),
                ('experience', models.IntegerField(default=0)),
                ('location', models.CharField(default='', max_length=100)),
                ('degree', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='student_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(default='', max_length=150)),
                ('year', models.CharField(choices=[('First', 'First'), ('Second', 'Second'), ('Third', 'Third')], default='First', max_length=10)),
                ('about', models.CharField(max_length=500)),
                ('dob', models.DateField(default=datetime.date.today)),
                ('experience', models.IntegerField(default=0)),
                ('location', models.CharField(default='', max_length=100)),
                ('degree', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='college',
        ),
        migrations.RemoveField(
            model_name='student',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='student',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='student',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='student',
            name='location',
        ),
        migrations.RemoveField(
            model_name='student',
            name='year',
        ),
        migrations.AddField(
            model_name='student_details',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='judge_details',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
