# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 13:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20170328_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='judge_details',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student_details',
            name='email',
        ),
        migrations.AddField(
            model_name='student',
            name='about',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='student',
            name='college',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='student',
            name='degree',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='designation',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='dob',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='student',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='industry_exp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.CharField(choices=[('First', 'First'), ('Second', 'Second'), ('Third', 'Third')], default='First', max_length=10),
        ),
        migrations.DeleteModel(
            name='judge_details',
        ),
        migrations.DeleteModel(
            name='student_details',
        ),
    ]
