# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20170328_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='website',
            field=models.EmailField(default='dummy@dummy.com', max_length=254),
        ),
    ]
