# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_student_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(height_field=245, null=True, upload_to='', width_field=220),
        ),
        migrations.AlterField(
            model_name='student',
            name='experience',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='industry_exp',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
