# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20170328_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(blank=True, height_field=245, null=True, upload_to='', width_field=220),
        ),
    ]
