# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20170329_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='club',
            field=models.BooleanField(default=False),
        ),
    ]
